[SA-18030] helm chart
appgate/sdp-k8s-client pull request #41
Opened 2021-12-16 11:06 UTC by kajes

Helm chart for easy deployment of the SDP Kubernetes Client using Helm.

2021-12-16 11:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appgate/sdp-k8s-client?pullRequest=41) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/appgate/sdp-k8s-client?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appgate/sdp-k8s-client?pullRequest=41) it.</sub>

2021-12-21 14:23 UTC, mandopaloooza requested changes

2021-12-21 14:23 UTC, mandopaloooza commented on k8s/chart/Chart.yaml
> +description: A Helm chart for Kubernetes
Probably want to update this description

2021-12-21 14:23 UTC, mandopaloooza commented on k8s/chart/values.yaml
> +  repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
I don't know how the `sdp-injector` image is tagged and pushed to this repository, but deployment.yaml will use `.Chart.appVesion` as the tag for the image to pull down. Looks like it's set to `0.1.0` at the moment. We should change the appVersion so that it refers to the actual version of the sdp-injector we are using.

2021-12-21 14:23 UTC, mandopaloooza commented on k8s/chart/values.yaml
> +  clientSecretName: sdp-injector-secrets
How is the secret created in the namespace? Does it need to be manually created before we deploy this chart?

2021-12-21 14:34 UTC, mandopaloooza commented on k8s/chart/values.yaml
> +  repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
I looked at the GH workflow and it looks like we're pushing `latest` and `${{ github.sha }}`. Might want to update the GH workflow so that this helm charts `.Chart.appVersion` also gets updated with every build.

```
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PROFILE=${{ steps.build-profile.outputs.PROFILE }}
          context: .
          file: docker/sdp-injector-Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-injector:latest
            ghcr.io/${{ github.repository }}/sdp-injector:${{ github.sha }}
```

2021-12-21 14:41 UTC, kajes commented on k8s/chart/values.yaml
> +  clientSecretName: sdp-injector-secrets
Yes, it needs to be manually created as far as I know.

2021-12-21 14:44 UTC, kajes commented on k8s/chart/values.yaml
> +  repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
The question is what kind of versioning we want to use for this. The chart is supposed to be public, so having some more readable versioning would probably help. Probably a later discussion though. You can set the container tag in values file when you deploy, and that's pretty much up to the user anyway.

2021-12-22 07:49 UTC, kajes commented on k8s/chart/values.yaml
> +  repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
We're probably going to come back to how the versioning should work. For now, we can control which image it should pull in the `values` when deploying.

2021-12-22 13:43 UTC, mandopaloooza commented on k8s/chart/values.yaml
> +  repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
I guess my only concern was that is image tag/version `0.1.0` is available on the repository if the user decides to simply run `helm install sdp-k8s-client/k8s/chart`. I think the best practice for publicly available helm chart is to default to the latest stable version.

2021-12-22 16:13 UTC, mandopaloooza approved these changes
Approving and merging to continue this work

2021-12-22 16:13 UTC, merged